### ISSUE TITLE
sjupyter: ssh-nomux

### ISSUE THREAD

**Issue by jabl** [AaltoScienceIT/triton-bin#1]
sjupyter prints out some instructions how to connect to the jupyter instance running on a compute node. One option it suggests is using a ssh ProxyCommand. However, what is this "ssh-nomux" it suggests? 

What I eventually got working was

From ~/.ssh/config:

<pre><code>
Host triton
     Compression yes
     ForwardAgent yes
     ProxyCommand ssh MYUSERNAME@taltta.aalto.fi -W %h.aalto.fi:%p
</code></pre>

And then connecting with 

`ssh -D SOME_RANDOM_PORT MYUSERNAME@triton`

And then configuring the web browser proxy for SOME_RANDOM_PORT. 

(There is actually a firefox add-on called "foxyproxy standard" which allows you to set up different proxy rules for different URL patterns, so you don't have to reconfigure the browser all the time)

**Comment by rkdarst** [comment]
Oh!  `ssh-nomux` is a special alias I have set up to disable the connection multiplexing.  I have this for all hosts, which means that if I open a new connection the forwardings don't work.
```
Host *
        ControlMaster   auto
        ControlPath     /tmp/.ssh-rkdarst-mux-ssh-%r@%h:%p
```
ssh-nomux is a shortcut to disable this: `alias ssh-nomux='ssh -o ControlMaster=no -o ControlPath=/nothere'` or something like that.  This should clearly not be in the script.  (it actually seems that multiplexing is more advanced than it used to be, maybe I should adjust now: https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing)

Also, if you add a `HostName triton....` to the ssh config block, you can use `-W %h:%p` and the same proxy command can be copied to anywhere.


FoxyProxy Standard is really nice.  I was using an extension "AutoProxy", but it was a bit buggy so I couldn't recommend it.  FoxyProxy seems better, I'm changing the description to recommend this first.  I think we still need to think about what the most clear and simplest way of supporting this is.  (maybe that's jupyterhub...)

I also took the opportunity to implement the `--list` function...

Please re-open or directly improve if things still need it...
